
# purge-delay: 10 # 审计日志清理时间间隔，默认 10s
health-check-path: health # 健康检查路由，默认为 /health
health-check-address: 0.0.0.0:7070 # 健康检查绑定端口，默认为 0.0.0.0:7070
# omit-detailed-recording: true # 设置为 true 会记录详细的授权审计日志，默认为 false

app_mode: ""
queue_region: ""

# Redis 配置
redis:
  host: "127.0.0.1" # redis 地址，默认 127.0.0.1:6379
  port: 6379 # redis 端口，默认 6379
  password: "" # redis 密码
  database: 0 # redis 数据库
  optimisation-max-idle: 100  # redis 连接池中的最大空闲连接数
  optimisation-max-active: 100 # 最大活跃连接数
  enable-cluster: false # 是否开启集群模式
  addrs:
  master-name: # redis 集群 master 名称
  username: # redis 登录用户名
  timeout: # 连接 redis 时的超时时间
  use-ssl: # 是否启用 TLS
  ssl-insecure-skip-verify: # 当连接 redis 时允许使用自签名证书

# 阿里云MNS配置
aliyunmns:
  endpoint: ""
  access_key_id: ""
  access_key_secret: ""

# RabbitMQ配置
rabbitmq:
  amqp_uri: "amqp://guest:guest@localhost:5672/"
  channel_pool_size: 10 # 连接channel的数量
  confirm_delivery: true # 是否保证消息到达
  exchange_name: "demo" # exchange

# Kafka配置
kafka:
  broker: "localhost:9092"
  ssl_cert_file: ""
  ssl_key_file: ""
  sasl_mechanism: ""
  sasl_username: ""
  sasl_password: ""
  sasl_algorithm: ""
  timeout: 0
  compressed: false
  use_ssl: false
  ssl_insecure_skip_verify: false

log:
    name: daemon # Logger的名字
    development: true # 是否是开发模式。如果是开发模式，会对DPanicLevel进行堆栈跟踪。
    level: info # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
    format: console # 支持的日志输出格式，目前支持console和json两种。console其实就是text格式。
    enable-color: true # 是否开启颜色输出，true:是，false:否
    disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
    disable-stacktrace: false # 是否再panic及以上级别禁止打印堆栈信息
    output-paths: ./daemon.log,stdout # 多个输出，逗号分开。stdout：标准输出，
    error-output-paths: ./daemon.error.log # zap内部(非业务)错误日志输出路径，多个输出，逗号分开


mq-default: Kafka
message-process-host: http://0.0.0.0:8080
processor-default: http
consumer-groups: COMMON,COMMON_DISTRIBUTE,BKK_DISTRIBUTE

mq-consumer:
  DistributeTasker:
    group: COMMON_DISTRIBUTE
    queue-name: topic-C
    group-id: consumer-group-id
    consumer-num: 4
    message-processor-num: 20
    mq-server: default
    processor: default
    url-path: /test3
  OrderDistribute:
    group: BKK_DISTRIBUTE
    queue-name: topic-C
    group-id: 
    consumer-num: 1
    message-processor-num: 20
    mq-server: Redis
    processor: default
    url-path: /test2
  OrderOpenRobDistribute:
    group: BKK_DISTRIBUTE
    queue-name: topic-C
    group-id: 
    consumer-num: 4
    message-processor-num: 20
    mq-server: RabbitMQ
    processor: default
    url-path: /test
